apiVersion: v1
kind: Pod
metadata:
  name: sql-server-pod
  labels:
    app: sql-server
spec:
  containers:
  - name: sql-server-container
    image: db_image:latest
    ports:
    - containerPort: 1433
    resources:
      limits:
        memory: "0.5Gi"  # 512 MiB = 0.5 GiB
        cpu: "500m"      # 500 millicores = 0.5 cores
      requests:
        memory: "256Mi"  # 256 MiB
        cpu: "250m"      # 250 millicores = 0.25 cores
  restartPolicy: Always
