apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: redis-container
        image: cache_image:latest
        ports:
        - containerPort: 6379
        resources:
          limits:
            memory: "0.5Gi"  # 512 MiB = 0.5 GiB
            cpu: "500m"      # 500 millicores = 0.5 cores
          requests:
            memory: "256Mi"  # 256 MiB
            cpu: "250m"      # 250 millicores = 0.25 cores
        
        # Add other container specifications for db-pod
      - name: sql-server-container
        image: db_image:latest
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: "0.5Gi"  # 512 MiB = 0.5 GiB
            cpu: "500m"      # 500 millicores = 0.5 cores
          requests:
            memory: "256Mi"  # 256 MiB
            cpu: "250m"      # 250 millicores = 0.25 cores

        # Add other container specifications for db-pod
      - name: dotnet-container
        image: dotnet_image:latest
        ports:
        - containerPort: 70
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          limits:
            memory: "0.5Gi"  # 512 MiB = 0.5 GiB
            cpu: "500m"      # 500 millicores = 0.5 cores
          requests:
            memory: "256Mi"  # 256 MiB
            cpu: "250m"      # 250 millicores = 0.25 cores

        # Add other container specifications for dotnet-pod
      - name: nginx-lb-container
        image: lb_image:latest
        ports:
        - containerPort: 60
        resources:
          limits:
            memory: "0.5Gi"  # 512 MiB = 0.5 GiB
            cpu: "500m"      # 500 millicores = 0.5 cores
          requests:
            memory: "256Mi"  # 256 MiB
            cpu: "250m"      # 250 millicores = 0.25 cores

        # Add other container specifications for lb-pod
      - name: rabbitmq-container
        image: mq_image:latest
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources:
          limits:
            memory: "0.5Gi"  # 512 MiB = 0.5 GiB
            cpu: "500m"      # 500 millicores = 0.5 cores
          requests:
            memory: "256Mi"  # 256 MiB
            cpu: "250m"      # 250 millicores = 0.25 cores
        # Add other container specifications for mq-pod
