apiVersion: v1
kind: Pod
metadata:
  name: dotnet-pod
  labels:
    app: dotnet
spec:
  containers:
  - name: dotnet-container
    image: dotnet_image:latest
    ports:
    - containerPort: 80
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: "Production"
    resources:
      limits:
        memory: "0.5Gi"  # 512 MiB = 0.5 GiB
        cpu: "500m"      # 500 millicores = 0.5 cores
      requests:
        memory: "256Mi"  # 256 MiB
        cpu: "250m"      # 250 millicores = 0.25 cores
  restartPolicy: Always
