# 2. Database Image: Contains your database server.

# Choose the appropriate base image for your database (e.g., SQL Server, PostgreSQL)
# Example for SQL Server
FROM mcr.microsoft.com/mssql/server:2019-latest
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD="Kerolos1234"
